spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.25.132/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.25.132
    port: 6379

server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.shm.sell.LoggerTest: debug
wechat:
  mpAppId: wxb875794e83822825
  mpAppSecret: 81a17c90710a33882f24f84199aa4bb7
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.com/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://e5buez.natappfree.cc
  wechatOpenAuthorize: http://sell.com
  sell: http://sell.com

logging:
  level:
    com.shm.sell.pojo.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
